# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(default=0)),
                ('class_level', models.IntegerField(default=0)),
                ('priority_level', models.IntegerField(default=0)),
                ('status_level', models.IntegerField(default=0)),
                ('stage_level', models.IntegerField(default=0)),
                ('product_version', models.CharField(max_length=30)),
                ('product_type', models.CharField(max_length=30)),
                ('change_date', models.DateTimeField(verbose_name=b'change date')),
            ],
        ),
    ]
