# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ispproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='area_name',
            field=models.CharField(default=b'', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='guest_name',
            field=models.CharField(default=b'', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='leader_name',
            field=models.CharField(choices=[(b'W', b'WenZhenYu'), (b'Z', b'ZhongLianBo')], default=b'W', max_length=1),
        ),
        migrations.AddField(
            model_name='project',
            name='pm_name',
            field=models.CharField(choices=[(b'C', b'Conner'), (b'G', b'Garvin'), (b'H', b'Harvey'), (b'W', b'Will')], default=b'C', max_length=1),
        ),
        migrations.AddField(
            model_name='project',
            name='rd_name',
            field=models.CharField(default=b'', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='product_type',
            field=models.CharField(choices=[(b'A', b'ADSL'), (b'B', b'BB')], default=b'A', max_length=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='product_version',
            field=models.CharField(default=b'1.0.0', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='status_level',
            field=models.CharField(choices=[(b'N', b'Normal'), (b'U', b'ABNORMAL')], default=b'N', max_length=1),
        ),
    ]
