# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 09:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ispproject', '0002_auto_20161117_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='isp',
            field=models.CharField(default=b'Default ISP', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='area_name',
            field=models.CharField(default=b'Default Area', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 28, 9, 45, 50, 947331, tzinfo=utc), verbose_name=b'change date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='class_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='guest_name',
            field=models.CharField(default=b'Default Guest', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='leader_name',
            field=models.CharField(default=b'Default Leader', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='pm_name',
            field=models.CharField(default=b'Conner', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='product_version',
            field=models.CharField(default=b'Default Version', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='rd_name',
            field=models.CharField(default=b'Default Research Engineer', max_length=30),
        ),
    ]
