# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 10:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ispproject', '0003_auto_20161128_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 28, 10, 15, 41, 133039, tzinfo=utc), verbose_name=b'change date'),
        ),
    ]
