# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ispproject', '0005_auto_20161128_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='change_date',
            field=models.DateTimeField(verbose_name=b'change date'),
        ),
    ]
